import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// https://github.com/rust-blockchain/evm

const langs = [
  {
    name: 'Solidity',
    desc: 'Object oriented, high level smart contract for EVM compatible blockchains',
    url: 'https://docs.soliditylang.org'
  },
  {
    name: 'Move',
    desc: 'Programming language based on Rust created by Facebook',
    url: 'https://move-book.com/'
  },  
  {
    name: 'Stateless',
    desc: 'Separated logic and state, Rust Base Smart Contracts by Solana and Near',
    url: '#'
  },    
  {
    name: 'Motoko',
    desc: 'Canister packed programming language by Internet Computer',
    url: 'https://internetcomputer.org/docs/current/developer-docs/build/cdks/motoko-dfinity/motoko/'
  },  
  {
    name: 'Cadence',
    desc: 'Resource oriented language for building contracts by Flow',
    url: 'https://developers.flow.com/cadence'
  },  
  {
    name: 'Clarity',
    desc: 'Decidable smart contract optimizing predictability by Stacks',
    url: 'https://docs.stacks.co/docs/write-smart-contracts/'
  },  
  {
    name: 'Archetype',
    desc: 'High level language for building verifiable contracts designed by Tezos',
    url: 'https://tezos.com/developers/archetype/'
  },
  {
    name: 'Ink (ink!)',
    desc: 'Substrate programming language in Rust compiled to WebAssembly',
    url: 'https://wiki.polkadot.network/docs/build-smart-contracts'
  },  
]

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HashCon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>HashCon</h1>

        <p className={styles.description}>
          Learn, innovate and mature blockchain <b>smart contracts</b>
          <span className={styles.descInner}>
            Audit to Earn | Submit Interface Proposals | Grow Developer Network
          </span>
        </p>

        <div className={styles.grid}>

          {
            langs.map(lang => (
              <a key={lang.name} href={lang.url} target="_blank" rel="noreferrer" className={styles.card}>
                <h2>{lang.name}</h2>
                <p>{lang.desc}</p>
              </a>
            ))
          }

        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://xircus.app" target="_blank" rel="noopener noreferrer">
          Powered by Xircus
        </a>
      </footer>
    </div>
  )
}
